### ISSUE TITLE
TypeError: Transliterator is not a constructor

### ISSUE THREAD

**Issue by zhondori** [diyorbek/lotin-kirill#8]
Assalamu alaikum.

I'm getting the error `TypeError: Transliterator is not a constructor`. How can i fix it ?

My code:

```js
import Transliterator from "lotin-kirill";

const transliterator = new Transliterator();

export default transliterator;

```

**Comment by diyorbek** [comment]
Vaalaikum assalam.

There's a problem with the build tool. For modules that are not ESNext you have to explicitly access `.default`.

```
import Transliterator from 'lotin-kirill'

const transliterator = new Transliterator.default()
```

Currently, I don't have capacity to work on this problem. Feel free to send a PR if you would like to.   :)
